### ISSUE TITLE
V1 Roadmap

### ISSUE THREAD

**Issue by LeoLeBras** [winoteam/react-router-navigation#56]
Here it is, the roadmap for `react-router-navigation` 1.0 :
* [x] Refactor `react-router-navigation-core` 🔥
* [x] Upgrade to `react-native@latest`
* [x] Upgrade to `react-navigation@latest` 🚀
* [x] Move to `workspace` structure
* [x] Add iPhone X support https://github.com/LeoLeBras/react-router-navigation/issues/55
* [x] Fix https://github.com/LeoLeBras/react-router-navigation/issues/30
* [x] ~~Fix https://github.com/LeoLeBras/react-router-navigation/issues/46~~
* [x] Fix https://github.com/LeoLeBras/react-router-navigation/issues/49
* [x] Fix https://github.com/LeoLeBras/react-router-navigation/issues/58
* [x] Fix https://github.com/LeoLeBras/react-router-navigation/issues/29
* [x] Fix https://github.com/LeoLeBras/react-router-navigation/issues/21
* [x] ~~Fix https://github.com/LeoLeBras/react-router-navigation/issues/57~~
* [x] ~~Fix https://github.com/LeoLeBras/react-router-navigation/issues/39~~
* [x] Fix https://github.com/LeoLeBras/react-router-navigation/issues/27
* [x] Fix https://github.com/LeoLeBras/react-router-navigation/issues/69
* [x] ~~Fix https://github.com/LeoLeBras/react-router-navigation/issues/73~~
* [x] ~~Fix https://github.com/LeoLeBras/react-router-navigation/issues/1~~
* [x] ~~Fix https://github.com/LeoLeBras/react-router-navigation/issues/76~~

**Comment by LeoLeBras** [comment]
Track changes on [stable](https://github.com/LeoLeBras/react-router-navigation/tree/stable)

**Comment by zachrnolan** [comment]
Hey @LeoLeBras, how are things progressing with V1? Please let me know if you need any help with any specific tasks or testing.

**Comment by LeoLeBras** [comment]
I decided to rewrite the library rather than finalize a v1, which allowed me to fix more major problems at the core level. To track the changes : https://github.com/winoteam/react-router-navigation/projects/1
@zachrnolan have you tried the new alpha version? have you noticed any bugs?
